# Generated by Django 3.2.8 on 2022-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('code_int', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('cost', models.CharField(blank=True, max_length=25, null=True)),
                ('price_1', models.CharField(blank=True, max_length=25, null=True)),
                ('price_2', models.CharField(blank=True, max_length=25, null=True)),
                ('price_3', models.CharField(blank=True, max_length=25, null=True)),
                ('price_4', models.CharField(blank=True, max_length=25, null=True)),
                ('price_5', models.CharField(blank=True, max_length=25, null=True)),
                ('tax', models.CharField(blank=True, max_length=3, null=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('download', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('new_product', models.BooleanField(default=False)),
                ('gerbe_1', models.BooleanField(default=True)),
                ('gerbe_2', models.BooleanField(default=True)),
                ('gerbe_3', models.BooleanField(default=True)),
                ('gerbe_4', models.BooleanField(default=True)),
                ('gerbe_5', models.BooleanField(default=True)),
            ],
        ),
    ]
